sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t sperlus/docker-react .

script:
  - docker run -e CI=true sperlus/docker-react npm run test
